name: Mutation Analysis

on:
  push:
    branches:
      - master
    paths-ignore: [ 'README.md', 'LICENSE.txt' ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: Run mutation analysis
        run: java -jar checker/target/checker-0.0.1-SNAPSHOT-jar-with-dependencies.jar checker/src/test/resources/org/polystat/py2eo/checker/simple-tests www
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www
          clean: false