name: Mutation Analysis

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build with Maven
        run: mvn clean package -DskipTests=true
      - name: Rename jar
        run: cp checker/target/checker-*-jar-with-dependencies.jar checker.jar
      - name: Run mutation analysis
        run: java -jar checker.jar transpiler/src/test/resources/org/polystat/py2eo/transpiler/ www
      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: www
          clean: false