name: Django runner

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Build with Maven
        run: mvn clean verify -B -Pdjango