name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: |
          wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz &&
          tar x -z < openjdk-17.0.2_linux-x64_bin.tar.gz &&
          mkdir .m2 && cp toolchains.xml ~/.m2 &&
          mvn clean compile -B

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
      - name: Build with Maven
        run: mvn clean test -B && cd ./runEO && mvn clean test
      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: src/test/resources/org/polystat/py2eo/genCageEO/
