name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:[macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean compile -B

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean test -B
      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: python/python3/test/genEO/

  runEO:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: ./python/python3/test/src/main/eo
      - name: Build with Maven
        run: mvn clean test -B -PrunEO