name: Java CI

on:
  push:
    tags:
      - *

jobs:

  polystatIntegration:
    strategy:
        matrix:
            os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    needs: test
    steps:
    - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Build with Maven
        run:  mvn clean package -B -DskipTests=true
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Download artifacts
        run: cp ./transpiler/target/transpiler-0.0.1-SNAPSHOT-jar-with-dependencies.jar ./
      - name: download polystat 
        run: wget https://repo.maven.apache.org/maven2/org/polystat/polystat/0.4.0/polystat-0.4.0-jar-with-dependencies.jar
      - name: translate python
        run: java -jar ./transpiler-0.0.1-SNAPSHOT-jar-with-dependencies.jar ./transpiler/src/test/resources/org/polystat/py2eo/transpiler/integrationTests/test.py
      - name: analysis
        run: cp ./transpiler/src/test/resources/org/polystat/py2eo/transpiler/integrationTests/genCageEO/test.eo ./transpiler/src/test.eo && cp ./transpiler/src/test/resources/org/polystat/py2eo/transpiler/integrationTests/goto.eo ./transpiler/src/goto.eo && java -jar ./polystat-0.4.0-jar-with-dependencies.jar ./transpiler/src ./temp --sarif
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: polystatResults
          path: /Users/runner/work/py2eo/py2eo/temp
      - name: failure artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: py2eo output
            path: ./transpiler/src/test.eo